# Generated by Django 6.0.7 on 2026-07-16 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0003_poitem_gst_rate_poitem_hsn_code_poitem_subtotal_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vendor',
            old_name='contact',
            new_name='contact_person',
        ),
        migrations.AddField(
            model_name='vendor',
            name='bank_account_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='bank_ifsc',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='bank_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='gst_no',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='pan_no',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
