# Generated by Django 6.0.7 on 2026-07-16 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0004_rename_contact_vendor_contact_person_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='registration_no',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
