# Generated by Django 6.0.7 on 2026-07-22 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0005_vendor_registration_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='status',
            field=models.CharField(choices=[('sent', 'Sent'), ('partially_received', 'Partially Received'), ('closed', 'Closed'), ('cancelled', 'Cancelled')], default='sent', max_length=20),
        ),
    ]
